apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy-svc
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: reverse-proxy
  type: LoadBalancer 