services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-api-user && docker build -t udagram-api-user .
  - docker tag udagram-api-user $YOUR_DOCKER_HUB/udagram-api-user:latest

  - cd udagram-api-feed && docker build -t udagram-api-feed .
  - docker tag udagram-api-feed $YOUR_DOCKER_HUB/udagram-api-feed:latest

  - cd .. && cd udagram-frontend && docker build -t udagram-frontend .
  - docker tag udagram-api $YOUR_DOCKER_HUB/udagram-frontend:latest

  - cd .. && cd udagram-reverseproxy && docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy $YOUR_DOCKER_HUB/udagram-reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - docker push $YOUR_DOCKER_HUB/udagram-api-user
  - docker push $YOUR_DOCKER_HUB/udagram-api-feed
  - docker push $YOUR_DOCKER_HUB/udagram-frontend
  - docker push $YOUR_DOCKER_HUB/udagram-reverseproxy
